### ISSUE TITLE
Superfecta is called before the Privacy Manager macro 

### ISSUE THREAD

**Issue by lgaetz** [POSSA/Caller-ID-Superfecta#144]
The code splice into [ext-did-xxxx] for Superfecta takes place immediately after the blacklist check but before the privacy manager macro. I think that Superfecta should splice after the privacy manager macro is called for cases where CID is supplied by the caller instead of by the trunk.

Also in the ext-did context is a line that sets blank CNAM to the CID but the trunk-provided lookup module is set to discard if CNAM == CID so should not be an issue.

First report of this issue:
http://pbxinaflash.com/community/index.php?threads/caller-id-superfecta-privacy-manager-issue.15884/

Ticket filed years ago here:
http://www.freepbx.org/trac/ticket/3455

**Comment by tm1000** [comment]
Splice before 'dest-ext' fixed in 12.x
