### ISSUE TITLE
source-CallWithUs.module update  (SVN and Git are opaque to new users)

### ISSUE THREAD

**Issue by adamgoldberg** [POSSA/Caller-ID-Superfecta#158]
The version of source-CallWithUs.module is almost entirely correct for v2.11 (it's listed as not migrated), but callwith.us changed their 'username'/'password' to 'apikey'/'password.

Changes are

1. replace 'username' with 'apikey'

    public $source_param = array(
        'apikey' => array(
                'description' => 'API key for CallWithUs, found on the CallWithUs MyAccount page',
                'type' => 'text'

2. change first $url to

            $url = "http://lrn.callwithus.com/api/cnam/index.php?key=".$run_param['apikey']."&password=".$run_param['password']."&number=" . $thenumber;

3. change send $url to

                 $url = "http://lrn.callwithus.com/api/cnam/index.php?key=".$run_param['apikey']."&password=".$run_param['password']."&number=1" . $thenumber;

*TESTED & WORKING*

ALSO, finally, can someone privately or otherwise point me at a simple recipie for using svn and git?  I'm totally lost (having never used either ... this is a long way from RCS ;)

**Comment by tm1000** [comment]
Fixed in 12.x
