### ISSUE TITLE
SPAM prefix missing from CNAM for known spam numbers with 2.11.5

### ISSUE THREAD

**Issue by lgaetz** [POSSA/Caller-ID-Superfecta#161]
I and another user have been testing improvements to the Who Called module so that CNAM is prefixed with the spam prefix variable for known spam numbers listed at who called. While testing, the SPAM prefix was working fine for me, but not working for the other user.  I then realized that I was testing with 2.11.3 and he was testing with 2.11.5, so I upgraded and immediately was able to reproduce the reported problem.

Issue:
In 2.11.5, when debugging with a known who called spam number against a series of configured modules, the spam prefix only appears on the final CNAM if the "who called" module is ordered last in the list of configured modules. During a live call, Superfecta will not proceed to the end of the configured modules if a CNAM is found before, basically rendering the spam prefix feature unusable. My testing in ver. 2.11.3 was fine, was there a change made to the way the spam prefix is coded between these two versions?

**Comment by tm1000** [comment]
Fixed in 12. basically if a source says "spam" then we set the variable to true, we do NOT allow it to be reset to false again. True stays true for the length of the scheme
