### ISSUE TITLE
If call is redirected to SPAM destination by Superfecta, it will not have the Superfecta CNAM

### ISSUE THREAD

**Issue by lgaetz** [POSSA/Caller-ID-Superfecta#162]
When configuring a Superfecta scheme, the option exists to redirect SPAM identified calls to an alternate destination. This redirect happens staring on line 63 of /agi/superfecta.agi. The CNAM that Superfecta finds is applied to the channel by asterisk dialplan (line 115 of functions.inc.php) only after superfecta.agi is finished. For this reason, spam redirected calls do not have the Superfecta CNAM nor the CNAM spam prefix.

Two possible approaches:
 1. Instead of redirecting within superfecta.agi, instead set an asterisk variable and relocate the spam redirect to asterisk dialplan to trigger if variable is set
 2. Move the lines that set CALLERID(name) from the asterisk dialplan to superfecta.agi. This is less desirable because superfecta.agi is already used for purposes other than inbound calls (i.e. outbound cnam lookup) and may have unintended consequences in those situations.

**Comment by tm1000** [comment]
It does now! (12.x)
