### ISSUE TITLE
Ver. 2.11.5 source post_processing functions missing functionality

### ISSUE THREAD

**Issue by lgaetz** [POSSA/Caller-ID-Superfecta#169]
While trying to work on ticket #168 I found necessary features missing when trying to code the post_processing function for source lookup modules:

<h3>$winning_source</h3>
The $winning_source variable is set on line 62 of includes/processors/superfecta_single.php with the line:
```php
$winning_source = $data;
```
I am pretty sure this value doesn't get passed from the function. 

Later in the same file, the post_processing function for each source module is called with this line:
```php
$caller_id = $source_class->post_processing($this->isCacheFound(), NULL, $this->first_caller_id, $run_param, $this->trunk_info['callerid']);
```
the second param passed is supposed to be the value of $winning_source, but it is hard coded now as NULL. 

$winning_source variable is not set properly in the get_results function and is not passed to the send_results function.

<h3>classes missing in send_results function</h3>
Since a value for $winning_source was not available to the post_processing function, I tried to do the lookup again with:
```php
$name = $astman->database_get('cidname', $thenumber);
```
The $astman class is not available from post_processing. Looking at includes/processors/superfecta_single.php there are differences between how the source classes are called in the get_results and the send_results functions. There may well be other classes missing from post_processing as well, I didn't test

Neither of these bugs is within my skill level to address.

**Comment by tm1000** [comment]
Resolved in 12.x
