### ISSUE TITLE
Superfecta removes leading +(digit) from CID

### ISSUE THREAD

**Issue by lgaetz** [POSSA/Caller-ID-Superfecta#198]
On lines 22-23 of /agi/superfecta.agi the code checks for a leading + digit and removes them if present. A leading + will probably interfere with most lookups, but what is the reasoning behind stipping the next digit?

I suggest that instead of the present behavior, that all non-digits be stripped from the CID, and leave all digits intact which the user is free to manipulate with dial rules if necessary.

**Comment by tm1000** [comment]
I agree with hesitations. There is another ticket here where the CID was a bunch of letters. Should this maybe be alphanumeric and that is it? If so the offending lines can be changed.

**Comment by subzero01** [comment]
Why is this issue closed? It is not fixed yet

**Comment by tm1000** [comment]
Because its fix in release 12
