### ISSUE TITLE
Superfecta special character error (ä,ö,ü)

### ISSUE THREAD

**Issue by tsk7mde** [POSSA/Caller-ID-Superfecta#203]
Launched AGI Script /var/www/html/admin/modules/superfecta/agi/superfecta.agi

 /var/www/html/admin/modules/superfecta/agi/superfecta.agi: CID Superfecta is Answering the Channel
 /var/www/html/admin/modules/superfecta/agi/superfecta.agi: CID Superfecta: Scheme is ALL
 /var/www/html/admin/modules/superfecta/agi/superfecta.agi: CID Superfecta: The DID passed from Asterisk is: 06XXXXX
 /var/www/html/admin/modules/superfecta/agi/superfecta.agi: CID Superfecta: The number passed from Asterisk is: 015XXXXXX
 /var/www/html/admin/modules/superfecta/agi/superfecta.agi: CID Superfecta: The CID name passed from Asterisk is: 0152XXXXXX
 /var/www/html/admin/modules/superfecta/agi/superfecta.agi: CID Superfecta: Executing Scheme..
 /var/www/html/admin/modules/superfecta/agi/superfecta.agi: CID Superfecta: Matched CID Rule: '0.X' with '0152XXXXX'
 /var/www/html/admin/modules/superfecta/agi/superfecta.agi: CID Superfecta: CID Determined to be: 'Schfer'
 /var/www/html/admin/modules/superfecta/agi/superfecta.agi: CID Superfecta: Attempting to set lookupcid
 /var/www/html/admin/modules/superfecta/agi/superfecta.agi: CID Superfecta: Success!

AGI Script /var/www/html/admin/modules/superfecta/agi/superfecta.agi completed, returning 0

------------------------------------

The name is incorrectly displayed "Schfer" -->>> Schäfer

(Test a phone number against the selected sources.)
 On the website in the tests ä appears

---------------------------------------

Website Output:

Debug Level:NONEINFOWARNALL

Debug is on and set at level 1
 The Original Number: 064XXXXX
 The Scheme: default
 Scheme Type: SINGLEFECTA
 SPAM Destination: 
 is CLI: false
 Debugging Enabled, will not stop after first result.
 Scheme Variables:Array
 (
 [SPAM_Text_Substitute] => N
 [SPAM_Text] => SPAM
 [multifecta_timeout] => 1.5
 [processor] => superfecta_single.php
 [Curl_Timeout] => 3
 [Prefix_URL] => 
 [spam_destination] => 
 [spam_interceptor] => N
 [DID] => 
 [CID_rules] => 0.X
 9|.X
 [SPAM_threshold] => 3
 [order] => 1
 [sources] => Asterisk_Phonebook,DeTeMedien_DE,Klicktel_DE
 )

Trunk Variables:Array
 (
 [channel] => NA
 [language] => NA
 [type] => NA
 [uniqueid] => 1133292843
 [callerid] => 06XXXXXXX
 [calleridname] => unknown
 [did] => 
 [context] => from-superfecta
 )

Matched CID Rule: '0.X' with '064XXXXX'
 Searching Asterisk Phonebook ... 
 'Schäfer XXXXX'
 result took 0.0013 seconds.

Searching http://www.detemedien.de/ for 064XXXXXX...
 'Schäfer XXXXX '
 result took 0.3510 seconds.

Searching http://www.klicktel.de for 064XXXXX...
 'Schäfer, XXXXX'
 result took 0.1997 seconds.

Post CID retrieval processing.
 Returned Result would be: Schäfer XXXX
 result took 0.5536 seconds.

---------------------------------

MySQL Conf:

[mysqld]
 datadir = /var/lib/mysql
 socket = /var/lib/mysql/mysql.sock
 user=mysql
 symbolic-links=0
 character-set-server=utf8
 collation-server=utf8_unicode_ci
 big-tables

[mysqld_safe]
 log-error=/var/log/mysqld.log
 pid-file=/var/run/mysqld/mysqld.pid

[client]
 default-character-set=utf8

[mysql]
 default-character-set=utf8

PHP Conf:

default_charset = "utf-8"

-------------------------

Data Source Name:

DeTeMedien DE
 Klicktel DE

--------------------------

Asterisk (Ver. 11.10.0)
FreePBX Framework 2.11.0.37
CID Superfecta 2.11.12
Operating system CentOS Linux 6.5 
Apache version 2.2.15
MySQL version 5.1.73 

-------------------------------

On SNOM and CDR-Rep. th ä,ö,ü not displayed.
 On CDR-Rep "Sch�fer XXXXX"
 On SNOM Schfer

**Comment by lorn10** [comment]
Hi to all
Little question, - what's the status of this error? I use FreePBX 5.211.65-21 with CID Superfecta 2.11.16 and this problem is still present. --> Letter ü is displayed as eA, letter ä is displayed eO, etc. Note, all internal calls are working properly.

At first I thought the problem was in the firmware of my Yealink T32G & T38G phones. But Yealink Support was not able to reproduce this issue. Therefore, this Superfecta error seems to be still present. Exist there any workaround? Thanks for any hints.

**Comment by lgaetz** [comment]
This issue is fixed, but requires the php mbstring module to be installed. At the CLI, if you type:
`php -m`
is mbstring listed as an installed module? If not, you need to enable it.

**Comment by lorn10** [comment]
Thanks for this fast answer! Yes, php mbstring was not installed. Installed it with "yum install php-mbstring" and then make http restart with "service httpd restart". It seems to work now. Thanks!
