### ISSUE TITLE
NextCaller now uses OAuth and does not work with current sources

### ISSUE THREAD

**Issue by jcwoltz** [POSSA/Caller-ID-Superfecta#214]
Hello,

NextCaller now uses OAuth1.0a. I can not authenticate with current source to use NextCaller as a lookup source. 

https://dev.nextcaller.com/documentation/authentication/

**Comment by eric-cgn** [comment]
@lgaetz Current implementation matches the published API and it's working fine for me. This is a very good source. Current implementation (in superfecta 2.11.16).
