### ISSUE TITLE
Enabling growl prevents module results appearing at handsets

### ISSUE THREAD

**Issue by themurman** [POSSA/Caller-ID-Superfecta#223]
Hello;
When I enable growl notifications, and test with debug, I receive growl notifications.

When I have an actual call, I do not receive growl notifications, nor do I receive lookup data on the phones. If I disable growl, I receive lookup data on the phones.

I have uninstalled and reinstalled the module, with no luck. 
I have selected and deselected several data sources, but have not found another source causing issue.

Currently I have active:
Superfecta Cache
Asterisk Phonebook
Can411

Versions:
Superfecta 2.11.14
PIAF 3.0.6.5
FreePBX 2.11.0.38
Asterisk 11.10.2
OS Centos 6.5
Incredible PBX 11.10

**Comment by tm1000** [comment]
Closing as out of date.
