### ISSUE TITLE
IsValidNumber() dropping valid UK numbers

### ISSUE THREAD

**Issue by LeeUK** [POSSA/Caller-ID-Superfecta#230]
if (!$this->IsValidNumber('UK', $thenumber)) {
            $this->DebugPrint("Skipping Source - Non UK number: {$thenumber}");
        }

Seems to drop valid UK numbers. e.g. 08437240459, 01134199985.

**Comment by ntadmin** [comment]
You may find

http://en.m.wikipedia.org/wiki/List_of_dialling_codes_in_the_United_Kingdom

helpful, as it also provides clarity on the different types of code, which may simplify the code. For example, 01134 strictly a dialling code 0113 with a seven digit local number starting with 4.

**Comment by lgaetz** [comment]
Updated `includes/superfecta_base.php`

Latest version: https://github.com/POSSA/Caller-ID-Superfecta/raw/release/2.11/includes/superfecta_base.php
