### ISSUE TITLE
Send to email 'From:' header. (raspbx)

### ISSUE THREAD

**Issue by rambo1152** [POSSA/Caller-ID-Superfecta#240]
Yesterday my ISP's SMTP server began refusing to relay messages with a spoofed 'from:' header,
so Superfecta send to email from  asterisk@noreply.raspbx.org has stopped.

Where is this stored please?

I have found 'noreply.raspbx.org' in  /etc/mailname, so that might be half the answer, if so where do I change 'asterisk@'?
Graham.

**Comment by lgaetz** [comment]
Good  idea. Support for specifying a from address is now added. You can upgrade by downloading:
https://raw.githubusercontent.com/POSSA/Caller-ID-Superfecta/develop/sources/source-Send_to_email.module

and saving to `<<webroot>>/admin/modules/superfecta/sources` chown to asterisk:asterisk
