### ISSUE TITLE
Request: source detail on CID/Connectwise

### ISSUE THREAD

**Issue by IanRVic** [POSSA/Caller-ID-Superfecta#243]
Hi,

A request only - it would be productive if there was a field on the source/connectwise with an optional text entry which would be inserted right before the caller ID name that appears

ie: Name match = 'John Smith'
Field data: 'CW_'
Result display: 'CW_John Smith'

OR: Name match = 'John Smith'
Field data: 'Cust: '
Result display: 'Cust: John Smith'

This would allow us to be instantly advised that the caller is a customer or at the very least inside our database so we know which way to be looking for creating records or adding notes to existing records.

thanks for the consideration

Ian

**Comment by IanRVic** [comment]
further thought: if the field was left blank, it would simply insert '' in front and continue to appear as it does currently - therefore making the use of the field optional

**Comment by lgaetz** [comment]
This is a simple request and can be accomplished with minor edits to the file:
`/var/www/html/admin/modules/superfecta/sources/source-ConnectWise.module`

I will get to it eventually, but If you want to tackle it yourself, you will need to add a new source param of type text with a name like `$source_param['prefix']` with a default of null. Then change the last line to return the $callerid with the prefix pre-pended like this:

`php
return $run_param['prefix'].$caller_id;
`

**Comment by IanRVic** [comment]
I just added a *_ to the code straight in - for now that's fine - and down
the road can tweak it or wait for an update

absolutely no rush and no pressure - it was a "if you're in there, that's
great/suggestion" and very much appreciated

**Comment by lgaetz** [comment]
This feature looks good but I have no way to test. Get the newest version of the module file from here:
https://raw.githubusercontent.com/POSSA/Caller-ID-Superfecta/release/2.11/sources/source-ConnectWise.module

**Comment by IanRVic** [comment]
Didn't work - I ran it and it loaded into my freepbx just fine - could add to the config file but when I ran test calls it didn't pull any data 

looking at the debug - here's what came back:

Searching ConnectWise ... 
Searching Companies ... 
Not found in Companies ... 
Searching Contacts ... 
Fatal error: Function name must be a string in /var/www/html/admin/modules/superfecta/sources/source-ConnectWise.module on line 201


also attached is the config I did where I hard coded in the "*_" for my purposes

<?php

/***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** *****
 * Module Dev notes:
 * 
 * 
 * Revision History: 
 *    v0.1.0: Initial Release Version by myitguy
 *    v0.1.1: Minor bug fix by bushbomb
 *    v0.1.2: More bug fixes id'd by bushbomb
 *    v0.1.3: Initial migration to 2.11 by lgaetz
 *    2014-08-22  Added user param to set the API version in the URL
 ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** ***** *****/

class ConnectWise extends superfecta_base {

	public $description = "Look up data in local or remote ConnectWise CRM.";
	public $version_requirement = "2.11";
	public $source_param = array(
		'DB_Site' => array(
				'description' => 'ConnectWise Site URL not including the initial https://',
				'type' => 'text',
		),
		'DB_Company' => array(
				'description' => 'ConnectWise Company ID',
				'type' => 'text',
		),
		'DB_User' => array(
				'description' => 'Integration Username to connect to ConnectWise.  This ID should have access to the Company, Contact and Reporting APIs',
				'type' => 'text',
		),
		'DB_Password' => array(
				'description' => 'Integration Password to connect to ConnectWise',
				'type' => 'password',
		),
		'Search_Type' => array(
				'description' => 'The ConnectWise type of entries that should be used to match the number',
				'type' => 'select',
				'option' => array (
					'1' => 'Companies Only',
					'2' => 'Contacts Only',
					'3' => 'Companies --> Contacts',
				),
				'default' => '3',
		),
		'Filter_Length' => array(
				'description' => 'The number of rightmost digits to check for a match. Enter zero to disable this setting',
				'type' => 'number',
				'default' => 10
		),
		'API_Version' => array(
				'description' => 'The part of the URL excluding slashes following the host name that indicates the API version, e.g. "v2014_4" or "v4_6_release" (without quotes)',
				'type' => 'text',
				'default' => 'v2014_4',
		),
	);

	function get_caller_id($thenumber, $run_param=array()) {
		$caller_id = null;

		$integration_site = $run_param['DB_Site'];
		$integration_company = $run_param['DB_Company'];
		$integration_user = $run_param['DB_User'];
		$integration_password = $run_param['DB_Password'];
		$varSearchType = $run_param['Search_Type'];
		if ($run_param['API_Version']) {
			$integration_apiver = $run_param['API_Version'];
		} else {
			$integration_apiver = 'v4_6_release';
		}

		$wquery_string = "";
		$wquery_result = "";
		$wresult_caller_name = "";
		$timeout = 5;					// keeping this as is for now but it is probably not necessary. If timeout is req'd it should be a user setting

		$this->DebugPrint("Searching ConnectWise ... ");
		
		if ($run_param['Filter_Length'] != 0) {
			if (strlen($thenumber) > $run_param['Filter_Length']) $thenumber = substr($thenumber, -$run_param['Filter_Length']);  // keep only the filter_length rightmost digits
		}

		// Search Companies
		if($run_param['Search_Type'] == 1 || $run_param['Search_Type'] == 3)  {
			$this->DebugPrint("Searching Companies ... ");
			$integration_xml = <<<EOT
				<FindPartnerCompaniesAction xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
				<CompanyName>$integration_company</CompanyName>
				<IntegrationLoginId>$integration_user</IntegrationLoginId>
				<IntegrationPassword>$integration_password</IntegrationPassword>
				<Conditions>PhoneNumber like "$thenumber"</Conditions>
				<OrderBy>CompanyID</OrderBy>
				<Limit>1</Limit>
				</FindPartnerCompaniesAction>
EOT;
			// Order of replacement
			$order  = array("\r\n", "\n", "\r");
			$replace = '';

			// Processes \r\n's first so they aren't converted twice.
			$integration_xml = str_replace($order, $replace, $integration_xml);

			$url="https://$integration_site/$integration_apiver/services/system_io/integration_io.asmx/ProcessClientAction?actionString=".urlencode($integration_xml);
			$ch = curl_init();
			curl_setopt ($ch, CURLOPT_URL, $url);
			curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
			$value = htmlspecialchars_decode(curl_exec($ch));
			curl_close($ch);

			$pattern = "/<CompanyName>(.*?)<\/CompanyName>/";
			preg_match_all($pattern, $value, $matches);
			if (count($matches[0])>1) {
				$wresult_caller_name = $matches[0][1];
			}
			else
			{
				$this->DebugPrint("Not found in Companies ... ");
			}
		}

		// Search Contacts
		if($run_param['Search_Type'] == 2 || $run_param['Search_Type'] == 3 && $wresult_caller_name =="")  {
			$this->DebugPrint("Searching Contacts ... ");
		
			$integration_xml = <<<EOT
				<RunReportQueryAction xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
				<CompanyName>$integration_company</CompanyName>
				<IntegrationLoginId>$integration_user</IntegrationLoginId>
				<IntegrationPassword>$integration_password</IntegrationPassword>
				<ReportName>ContactCommunication</ReportName>
				<Conditions>Contact_Communication_Desc like "$thenumber"</Conditions>
				<Limit>1</Limit>
				</RunReportQueryAction>
EOT;
			// Order of replacement
			$order  = array("\r\n", "\n", "\r");
			$replace = '';

			// Processes \r\n's first so they aren't converted twice.
			$integration_xml = str_replace($order, $replace, $integration_xml);

			$url="https://$integration_site/$integration_apiver/services/system_io/integration_io.asmx/ProcessClientAction?actionString=".urlencode($integration_xml);
			$ch = curl_init();
			curl_setopt ($ch, CURLOPT_URL, $url);
			curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
			$value = htmlspecialchars_decode(curl_exec($ch));
			curl_close($ch);

			$pattern = '/<Value Name="Contact_RecID" Type="Numeric" IsNullable="false">(.*?)<\/Value>/';
			preg_match($pattern, $value, $match_ContactID);
			if (count($match_ContactID)>0)  {
				$integration_xml = <<<EOT
					<FindPartnerContactsAction xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
					<CompanyName>$integration_company</CompanyName>
					<IntegrationLoginId>$integration_user</IntegrationLoginId>
					<IntegrationPassword>$integration_password</IntegrationPassword>
					<Conditions>ContactRecID = $match_ContactID[1]</Conditions>
					<OrderBy>LastName</OrderBy>
					<Limit>10</Limit>
					</FindPartnerContactsAction>
EOT;
				// Order of replacement
				$order  = array("\r\n", "\n", "\r");
				$replace = '';

				// Processes \r\n's first so they aren't converted twice.
				$integration_xml = str_replace($order, $replace, $integration_xml);

				$url="https://$integration_site/$integration_apiver/services/system_io/integration_io.asmx/ProcessClientAction?actionString=".urlencode($integration_xml);
				$ch = curl_init();
				curl_setopt ($ch, CURLOPT_URL, $url);
				curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
				curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
				$value = htmlspecialchars_decode(curl_exec($ch));
				curl_close($ch);

				$pattern = "/<LastName>(.*?)<\/LastName>/";
				preg_match($pattern, $value, $match_LastName);

				$pattern = "/<FirstName>(.*?)<\/FirstName>/";
				preg_match($pattern, $value, $match_FirstName);
				if (count($match_LastName)>0 && count($match_FirstName)>0) {
					$wresult_caller_name = "*_". $match_FirstName[1]." ".$match_LastName[1];
				}
			}
			if ($wresult_caller_name =="")  {
				$this->DebugPrint("Not found in Contacts ... ");
			}
		}

		
		if(strlen($wresult_caller_name) > 0) {
			$caller_id = strip_tags($wresult_caller_name);
		}
		else if($debug) {
			$this->DebugPrint("Not found in ConneceWise");
		}
		return $caller_id;
	}
}

**Comment by lgaetz** [comment]
on it, give me a sec

**Comment by lgaetz** [comment]
Try it again by downloading with same link from above.

**Comment by IanRVic** [comment]
works perfectly - thank you!

**Comment by IanRVic** [comment]
small glitch - just noticed today - if connectwise is first in the list and there's no customer matching #, then anything subsequent doesn't get matched as it's already "found a name" (albeit one character) - 

in my non php speak - if name match = true then "prefix"+name else no prefix at all

**Comment by IanRVic** [comment]
purely my 2¢ (don't know if it will work in these places)

for first + last

$wresult_caller_name = < CNAM_prefix HERE> $match_FirstName[1]." ".$match_LastName[1];


for companies up higher:
if (count($matches[0])>1) {
$wresult_caller_name = <CNAM_prefix HERE> $matches[0][1];

**Comment by lgaetz** [comment]
The fix is to change line 201 to:
```php
$caller_id = $run_param['CNAM_prefix'].trim(strip_tags($wresult_caller_name));
```
Give it a try.

**Comment by IanRVic** [comment]
so far so good :)

**Comment by lgaetz** [comment]
Thanks
