### ISSUE TITLE
Local.ch broken

### ISSUE THREAD

**Issue by marcelser** [POSSA/Caller-ID-Superfecta#252]
Just tried using Superfecta on FreePBX stable but local.ch script is broken. When I debug phone number against it content is returned but no matches dumped. Please update and release new FreePBX Module.

**Comment by lgaetz** [comment]
Module has been updated (see #244) but not yet published. You can manually upgrade [downloading the latest version](https://github.com/POSSA/Caller-ID-Superfecta/raw/release/2.11/sources/source-LocalTel_CH.module) and replacing the file:
/var/www/html/admin/modules/superfecta/sources/source-LocalTel_CH.module
