### ISSUE TITLE
Lookup source request: Microsoft SQL Server

### ISSUE THREAD

**Issue by axlb** [POSSA/Caller-ID-Superfecta#275]
First and foremost i would like to thank everyone who is involved in developing this
 very useful project.

I've been implementing elastix/freepbx solutions on customers and i know that Callerid information is an important characteristic. Which brings me to my request. In many situations there is the need to connect to a microsoft SQL server in order to get Callerid data.
Unfortunately in the current version there is no mssql driver (there is MySQL and SQLite). The fact is that many installations use mssql for their CRM system and we could use this database as a lookup source. I think that in previous versions there existed such a driver.
Is there any plan to include a mssql driver in future versions? That would be great!

Thanks again

**Comment by tm1000** [comment]
You can do this with: https://github.com/POSSA/Caller-ID-Superfecta/blob/release/13.0/sources/source-SFDatabase.module
