### ISSUE TITLE
whocalled.us data source doesnt work

### ISSUE THREAD

**Issue by wa4zlw** [POSSA/Caller-ID-Superfecta#276]
looks like something moved

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by jfinstrom** [comment]
http://issues.freepbx.org/browse/FREEPBX-10011 this has been long fixed. You are using old code

**Comment by wa4zlw** [comment]
can this be fixed?

thanks leon

**Comment by wa4zlw** [comment]
2.11.16 is what is on the distro and if I do a MODULE ADMIN and CHECK FOR UPDATES nothing new gets pulled.

leon

**Comment by tm1000** [comment]
Superfecta no longer receives updates for FreePBX 12. We only push updates for FreePBX 13.
