### ISSUE TITLE
OpenCNAM doesnt see to return any data using Superfecta

### ISSUE THREAD

**Issue by wa4zlw** [POSSA/Caller-ID-Superfecta#279]
did something change here too?

**Comment by wa4zlw** [comment]
seemed to return TOLL FREE CALL on an 8xx number but I've seen debugs where it didnt return any data

**Comment by jfinstrom** [comment]
Are you authenticating? They no longer allow unauthenticated requests

**Comment by wa4zlw** [comment]
ok that solved it. I incorrectly assumed that since there is a separate 
OpenCNAM plugin that it used that authentication - dah :-)
