### ISSUE TITLE
Raspbx - 	Send to URL

### ISSUE THREAD

**Issue by menexa** [POSSA/Caller-ID-Superfecta#283]
When I try with **Debug / Test Run Scheme** the module **Send to url** works perfectly but when I get a real call it does not work.
My scheme is
1. Asterisk Phonebook
2. GoogleContacts
3. Superfecta Cache
4. Send to URL (the url is another raspberry IP in the same local network)

**Version**
Asterisk: 11.22.0
FreePBX: 13.0.113
Caller-ID-Superfecta: 13.0.3.12 

I have cecked **php -i | grep -i "cURL Information"** and the result was **cURL Information => 7.38.0**
Any suggestion?

**Comment by lgaetz** [comment]
closing as duplicate
