### ISSUE TITLE
Post_Processing defect found (w/ fix) [FreePBX module]

### ISSUE THREAD

**Issue by doughoyt** [POSSA/Caller-ID-Superfecta#292]
Superfecta module: 13.0.3.19.1

Found a defect in: modules/superfecta/includes/processors/superfecta_single.php

In the send_results() method, code is 'including' the $source_name, rather than $source_file (likely borrowed from the get_results() method earlier where $source_name was full path).

If you change the file_exists test and include lines to use $source_**file** instead of $source_**name**, then post processing methods will be called for all sources.

``` php
              // Run the source
              $source_file = $this->path_location . "/source-" . $source_name . ".module";
              $class = "\\".$source_name;
              if (file_exists($source_file) && !class_exists($class)) {
                      include $source_file;
              }
```

**Comment by doughoyt** [comment]
A short-term work-around (that does not require a code change and FreePBX tampering warning) appears to be putting the "Send To" sources at the very top of the order (even before the cache).  The idea is that the send_to classes sources will be 'included' while enumerating all of the sources during the get_results method (and never be the "winner" source, so a later source will still be used) ... then, during send_results, the post_processing method will be found for the class since it was previously loaded via include.

**Comment by polcape** [comment]
With the last update, also change the line as reported @doughoyt  in the first pot not working anymore

**Comment by lgaetz** [comment]
fixed with commit:
https://git.freepbx.org/projects/FREEPBX/repos/superfecta/commits/8ee121b8a339931fa0f7a6d5a7632c81283e33f7

closing ticket
