### ISSUE TITLE
v2.2.5 sources left to migrate to v3.x

### ISSUE THREAD

**Issue by ukstevef** [POSSA/Caller-ID-Superfecta#42]
The following need to be converted.

* **Argentina**
 * <DEL>Paginasblancas_AR</DEL>
* **Austria**
 * <del>Herold_AT</del>
* **Australia**
 * <DEL>Google_Maps_AU</DEL>  <-- scheduled for deletion
 * Personlookup_AU
 * ReverseAustralia_AU
 * Reversephones_AU   <-- updated since migration
 * Superpages_AU
 * <del>Truelocal_AU</del>   <-- automated searches prohibited by TOS
 * Yellowpages_AU
* **Canada**
 * <DEL>Can411</DEL>   <-- TOS do not restrict Superfecta usage
 * <DEL>Can_White_Pages</DEL>  <-- automated searches prohibited by TOS
 * <del>CanPagesCa</del>  <-- automated searches prohibited by TOS
 * <del>Can_Yellow_Pages</del>  <-- automated searches prohibited by TOS
 * <del>Canada411</del>  <-- automated searches prohibited by TOS
* **Database**
 * <del>AsteriDex</del>
 * Elastixphonebook
 * <del>FOP2_Phonebook</del>
 * MSSQL_DB
 * <del>MySQL_DB</del> superseded by SFDatabase
 * <del>Open79XX</del>
 * PostgreSQL_DB
 * <del>SugarCRM</del>   <-- see #66 
 * <del>Theaddressbook</del>
 * VTiger_CRM
* **Dominican Republic**
 * <DEL>Paginasamarilla_DO</DEL> - Issue #56
* **Italy**
 * <DEL>PagineBianche_IT</DEL>
* **Netherlands**
 * <DEL>Gevonden #63</DEL> 
* **Serbia**
 * Telekom_rs_SR
* **Sweden**
 * <del>Eniro_SE</del>
 * <DEL>Hitta_SE</DEL> scraping prohibited
 * <del>Vemringde_SE</del>
 * <del>www_118700_SE</del>
* **USA**
 * CallWith.us
 * <del>Yellow Pages</del> automated search prohibited
 * <DEL>EnumQuery</DEL>
 * <DEL>Google</DEL> - See issue #37
 * Metrostat_US
 * <DEL>PhoneSpamFilter</DEL>
 * Telepest_US
 * <DEL>VoIPCNAM</DEL>
 * <del>OpenCNAM</del>
 * <del>Who Called</del>
* **Miscellaneous**
 * <del>Abandon_lookup</del>
 * <del>Trunk Provided</del>     <-- can't migrate, total rewrite
* **Post Processing**
 * <DEL>Send_to_Dreambox</DEL>
 * <DEL>Send_to_Squeezebox_Server</DEL>
 * <DEL>Send_to_Winunciator</DEL>
 * <del>Send_to_XBMC</del>
 * <del>Send_to_MythTV</del>
 * <del>Send_to_Email</del>
 * <del>Send_to_URLl</del>
 * <del>Send_to_Yac</del>
 * Send_to_Soundbridge
 * Send_to_SMS

* **Germany/German** - Issue #167 
 * <del>DeTeMedien</del>
 * <del>Klicktel</del>
 * <del>Infobel</del>
 * <del>Local.ch</del>

**Comment by tm1000** [comment]
Closing this as most of it is done. New tickets can be opened if needed. Trying to clean up the mess here
